services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $registeredTypes: "%doctrine.dbal.connection_factory.types%"
  
  Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser:
    class: Fresh\DoctrineEnumBundle\Form\EnumTypeGuesser
