risky: true
preset: symfony
tab-width: 4
use-tabs: false
version: 8.4
enabled:
  - combine_consecutive_unsets
  - ordered_class_elements
  - alpha_ordered_imports
  - declare_strict_types
  - symfony_phpdoc_order
disabled:
  - no_superfluous_phpdoc_tags_symfony
  - native_function_invocation_symfony
finder:
  exclude:
    - "Tests"
    - "vendor"
  name:
    - "*.php"
