preset: symfony

enabled:
  - combine_consecutive_unsets
  - linebreak_after_opening_tag
  - ordered_class_elements
  - ordered_imports
  - declare_strict_types

finder:
  exclude:
    - "Tests"
  name:
    - "*.php"
